# Site settings
title:              Yuriy Pakhotin
copyright:          "&copy; Yuriy Pakhotin"
baseurl:            ""
url:                "https://pakhot.in"
cover:              /assets/background1_3200x1600.jpg
disqus_shortname:   pakhotin

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
  math_engine: mathjax
include: ['_pages']
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

plugins:
    - jekyll-remote-theme
remote_theme: daattali/beautiful-jekyll
